
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: api_empresa
  pool: 5
  username: gleison
  password: XXXXXXXX
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: api_empresa
  pool: 5
  username: gleison
  password: XXXXXXXXX
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: api_empresa
  pool: 5
  username: gleison
  password: XXXXXXXX